version: "3.1"

networks:
  src: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  mysql:
    build: ./db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    networks:
      src:
        ipv4_address: 172.10.3.2
    env_file:
      - ./development.env
  www:
    build: ./www
    volumes: 
      - ./src:/var/www/html/
    ports:
      - 8888:80
    networks:
      src:
        ipv4_address: 172.10.2.2
    depends_on:
      - mysql
    env_file:
      - ./development.env
